### ISSUE TITLE
server returns error

### ISSUE THREAD

**Issue by qwedc001** [kvarenzn/phisap#3]
拿来测试一下（顺便AP db Doll）（划掉）
然后程序server端报错

**Comment by qwedc001** [comment]
我一开始以为是架构和提供的预编译release不同，于是自己用Android Studio重新编译了一份，但是仍然报错
报错信息如下
[server] INFO: 屏幕尺寸: 1920x1080
[server] INFO: 主控制进程已启动
[server] INFO: 流式传输已启动
[server] ERROR: 流式传输意外终止
[server] ERROR: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2063)
        at com.rabbithouse.svr.VideoStreamer.loop(VideoStreamer.kt:56)
        at com.rabbithouse.svr.Server.startStreaming$lambda-1(Server.kt:53)
        at com.rabbithouse.svr.Server.lambda$eVOR7URhW9s2eufKmQwzqeP1mGs(Unknown Source:0)
        at com.rabbithouse.svr.-$$Lambda$Server$eVOR7URhW9s2eufKmQwzqeP1mGs.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:784)

**Comment by qwedc001** [comment]
测试设备为华为荣耀畅玩6X（很老的机器了）
本人db Doll已经AP（废话）
在未终止电脑python程序运行的情况下直接拔掉手机数据线还会导致手机重启，这是什么原理

**Comment by kvarenzn** [comment]
啊这，百度了一下，畅玩6X系统版本貌似最高为Android 7，不知道您的安卓系统版本为多少？

流式传输那块用到了某些Android O(8.0)以上才支持的API,所以会崩。不过流式传输也没什么实际作用，就是一个与游戏内计时器粗略同步的方式（实测比不加要管点用，如果使用点击继续按钮就直接delay的方式会导致每次都得大幅调整delay的时长）。等下一个版本更新我会放出一个无需流式传输的版本。不过，如果您有闲功夫且愿意帮忙的话，请您尝试一下[scrcpy](https://github.com/Genymobile/scrcpy)能不能在您的设备上正常工作，如果能的话，请告知我，我会尝试修复这个问题。（或许吧 

本人没用过华为设备，拔掉数据线就会重启我估计是华为adb server的实现方式有问题。本程序相当于是在手机上开了个服务器来跟电脑传输数据（通过usb），直接拔掉或许会导致手机端的服务器崩溃，这个服务器的实现是系统级的，所以会导致崩溃（瞎猜的不一定对，本人用一加手机没遇到过这种情况）。如果您在使用[scrcpy](https://github.com/Genymobile/scrcpy)时直接拔线仍会遇到重启的问题，那就不是我这实现的问题了（

**Comment by qwedc001** [comment]
版本号Android 8.0.0
EMUI版本8.0.0

**Comment by qwedc001** [comment]
scrcpy正常工作，一会提供截图
并且直接拔线不会出现手机重启问题

**Comment by qwedc001** [comment]
![QQ截图20210823164746](https://user-images.githubusercontent.com/14366166/130418393-7f6505f7-bb2c-46ab-b3d8-59f4a55f9d33.png)

**Comment by qwedc001** [comment]
QQ：2364319479
如果您决定尝试复现这个bug的话可以加我QQ，我其他社交平台不活跃x

**Comment by qwedc001** [comment]
所以有头绪吗，既然我手机符合条件还会出错的话，问题能定位在server的什么位置上

**Comment by kvarenzn** [comment]
根据报错问题出在VideoStreamer.kt，肯定是MediaCodec那里配置有问题，或许是MediaFormat配置有误。

我从scrcpy那里借鉴的时候简化了很多适配其他机型的逻辑，估计再补上就没啥问题了（

**Comment by qwedc001** [comment]
好的，我可以在8月29日之前以我的机型提供测试帮助，之后每两周可以做一次测试（学生党马上开学了）
这或许是催促您不咕咕2.0的最好理由罢（（

**Comment by kvarenzn** [comment]
好的，非常感谢您能提供帮助

（同学生党，也马上开学，这或许可以是咕咕的理由
