### ISSUE TITLE
main.py运行错误

### ISSUE THREAD

**Issue by Q78KG** [kvarenzn/phisap#36]
`Traceback (most recent call last):
  File "C:\Users\Q78KG\Desktop\phisap\main.py", line 11, in <module>
    from catalog import Catalog
  File "C:\Users\Q78KG\Desktop\phisap\catalog.py", line 5, in <module>
    from binary_reader import BinaryReader
  File "C:\Users\Q78KG\Desktop\phisap\binary_reader.py", line 7, in <module>
    class BinaryReader:
  File "C:\Users\Q78KG\Desktop\phisap\binary_reader.py", line 23, in BinaryReader
    _header_backup: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

[已退出进程，代码为 1 (0x00000001)]`

**Comment by ClankySun10936** [comment]
U4 Python 10
