### ISSUE TITLE
解包时出现错误

### ISSUE THREAD

**Issue by aquawius** [kvarenzn/phisap#38]
进行解包时,运行出现错误后无反应
解包的版本为`2.4.5`,其中在`./Assert/Tracks`中出了一部分数据,但是不完整

控制台的tracert back返回如下
``` shell
PS D:\coding\phisap> python main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\coding\phisap\main.py", line 52, in extract_apk
    obj.get_image().save(asset_name)
AttributeError: 'NoneType' object has no attribute 'save'
```

**Comment by kvarenzn** [comment]
最近没有跟进最新版，看起来应该是鸽游换了新的`Texture2D`存储方式了。稍后修复。

**Comment by kvarenzn** [comment]
（可能）已修复

**Comment by aquawius** [comment]
经过测试, 已经修复解包问题(`main`分支下), 希望可以同步到`extended`分支

**Comment by kvarenzn** [comment]
`extended`分支已经无限期暂停开发了，而且现在也不能用，就不同步过去了
