### ISSUE TITLE
开始之后毫无反应

### ISSUE THREAD

**Issue by zzy6011** [kvarenzn/phisap#39]
先来说点题外话，第一次看到这个项目好像是在22年9月左右，那时候是想开寄于是就上网搜索“phigros自动打歌”（没错主播是yyw!)，然后就找到了这个项目。下载之后遇到的第一个问题是py安装，因为那时候啥也不懂，于是自己上网查（，好不容易装好之后就遇到了阻碍我开寄的最大问题：`pip install -r requirements.txt`，这里lz4死活安装不了，后来看到了一个issue和我相同问题，说是要安装什么windows visual什么什么的（好像是这个样子的罢？）然后安装完后发现装不下，然后就摆烂。之后又重新尝试安装lz4,发现`pip install lz4`能装上其他版本的，但是运行`main.py`之后报错no module found named"lz4.stream"(忘了，大概是这样报错）。然后就鸽了几个月，最后在上上周用whl安装好了lz4!!!接下来又碰到了问题，啊对，就是这个issue要问的（自己实在是解决不了了）
![image](https://user-images.githubusercontent.com/117558117/212690784-35885db5-dc51-4345-8853-48e683bff7bc.png)
如上图👆
点击开始后没有反应
从上上周一直到现在都没找到解决方法（（

**Comment by kvarenzn** [comment]
给出的信息不足，不过猜测可能是adb相关的问题。你可以尝试一下[scrcpy](https://github.com/Genymobile/scrcpy)这个项目，看看能否正常工作？如果scrcpy可以正常工作的话，那么就是phisap本身的问题，否则就不是

**Comment by zzy6011** [comment]
`C:\Users\Administrator>scrcpy
scrcpy 1.22 <https://github.com/Genymobile/scrcpy>
C:\Users\Administrator\Desktop\phisap-main\scrcpy-server: 1 file pushed, 0 skipped. 65.2 MB/s (40955 bytes in 0.001s)
[server] INFO: Device: vivo V2054A (Android 11)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x2408
WARN: Device disconnected
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2158)
        at android.media.MediaCodec.configure(MediaCodec.java:2074)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:274)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:326)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:433)
WARN: Killing the server...`

**Comment by zzy6011** [comment]
![image](https://user-images.githubusercontent.com/117558117/212814323-9d2e3121-ad20-49b3-b436-4a3d0a64c73c.png)
如图

**Comment by kvarenzn** [comment]
看起来scrcpy没有正常工作啊...很遗憾，这个问题我修复不了，这算是上游的问题

**Comment by zzy6011** [comment]
嘿，我又回来了
经过我的一系列我自己都不知道的神奇操作后，它终于有点反应了
![image](https://user-images.githubusercontent.com/117558117/214311499-21b91333-acdc-4cc7-a225-210f123963b1.png)
如图，他会一直循环这个玩意
哦对了，我用网上的方法成功运行这玩意了
![image](https://user-images.githubusercontent.com/117558117/214311761-50b17a9f-63e0-4117-b8d7-92b875b206a5.png)
![image](https://user-images.githubusercontent.com/117558117/214311791-18b6ac2f-dbfa-4288-85a7-6a0601eb435a.png)
