### ISSUE TITLE
无法进行操作

### ISSUE THREAD

**Issue by how2che4t** [kvarenzn/phisap#53]
正在统计帧...统计完毕，当前谱面共计23302帧
正在规划触控事件...规划完毕.
.\scrcpy-server-v1.25: 1 file pushed, 0 skipped. 89.2 MB/s (42151 bytes in 0.000s)
(184, 80)
[server] ERROR: Encoding error: android.media.MediaCodec$CodecException: Error 0xfffffc0e
Exception in thread Thread-1 (collector):
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2176)
        at android.media.MediaCodec.configure(MediaCodec.java:2092)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:282)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:97)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
Exception in thread Thread-2 (ctrlmsg_receiver):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "d:\Downloads\phisap-main (2)\phisap-main\control.py", line 50, in collector
    self._target(*self._args, **self._kwargs)
  File "d:\Downloads\phisap-main (2)\phisap-main\control.py", line 59, in ctrlmsg_receiver
    _pts, size = struct.unpack('!qI', header)
    size, = struct.unpack('!I', self.control_socket.recv(4))
struct.error: unpack requires a buffer of 12 bytes
struct.error: unpack requires a buffer of 4 bytes

**Comment by kvarenzn** [comment]
看报错是scrcpy的视频编码器崩溃了，我正在适配scrcpy 2.0.0，或许可以解决这个问题
