### ISSUE TITLE
关于一些精确度的问题

### ISSUE THREAD

**Issue by ABYSSOLITE1** [kvarenzn/phisap#58]
为什么在遇到hold锁手配置的时候另外一边的note会有延迟导致good或者连续miss，是模拟器不支持多点触控吗

https://user-images.githubusercontent.com/131573016/233820649-aabcd81c-8b96-4d4f-bf7e-b7527c84b22e.mp4

**Comment by kvarenzn** [comment]
确实有可能，或者可能是模拟器支持多点触控但不支持十指触控。具体只能看模拟器的表现了，雷电模拟器我没用过，不清楚
不过请问你使用的规划算法是哪个？我看着像是algo1，可以尝试一下algo2

**Comment by ABYSSOLITE1** [comment]
是algo2，那么这个程序是可以在模拟器上运行的是吗，我还以为不支持，我去换个模拟器试试

**Comment by kvarenzn** [comment]
理论上是可以在模拟器上运行的，而且之前有人说他在模拟器上跑的

**Comment by ABYSSOLITE1** [comment]
可是我换了其他模拟器又莫名其妙不行了

**Comment by kvarenzn** [comment]
看报错像是`adb push`文件时出的错
不过我确实没用过win上的安卓模拟器，因此也没法提供什么建议，抱歉
只能说这确实是模拟器的问题，因为迷宫 AT16这首曲子是能用phisap打出φ的

**Comment by ABYSSOLITE1** [comment]
是我没有开启模拟器adb功能，但是我开启后又报错了，我换了三次模拟器，雷电，夜神，这次是蓝叠，但是这次报错的类型好像和夜神的那个一样，可能是服务端的问题，但是不知道问题是什么
.\scrcpy-server-v1.25: 1 file pushed, 0 skipped. 18.6 MB/s (42151 bytes in 0.002s)
(184, 104)
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: start failed
Exception in thread Thread-1 (collector):
Exception in thread Thread-2 (ctrlmsg_receiver):
Traceback (most recent call last):
Traceback (most recent call last):
  File "E:\Users\qq809\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "E:\Users\qq809\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    self.run()
  File "E:\Users\qq809\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
  File "E:\Users\qq809\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2068)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:100)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
        at com.genymobile.scrcpy.Server.main(Server.java:334)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:365)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "C:\Users\qq809\Desktop\phisap-main\control.py", line 59, in ctrlmsg_receiver
  File "C:\Users\qq809\Desktop\phisap-main\control.py", line 50, in collector
    size, = struct.unpack('!I', self.control_socket.recv(4))
struct.error: unpack requires a buffer of 4 bytes
    _pts, size = struct.unpack('!qI', header)
struct.error: unpack requires a buffer of 12 bytes
[client] INFO: 自动打歌已结束

**Comment by kvarenzn** [comment]
这算是个老问题了，你翻翻issues可以看到很多人都提过这事
确实是scrcpy服务端的问题，对于一些机型（包括模拟器），scrcpy的视频编码器会崩溃
scrcpy自己有一套回退的解决方案，也就是当编码器崩溃后，客户端再尝试另一种编码器，不过这套方案目前phisap还没有实现
一个临时可行的解决办法是在control.py的第31行之后插入一行`'encoder_name=OMX.google.h264.encoder',`。参考issue #52
