### ISSUE TITLE
发送触控事件报错

### ISSUE THREAD

**Issue by sgg64587** [kvarenzn/phisap#68]
设备系统是Android13的MIUI14  scrcpy版本为2.0.0 phisap为最新版本 在点击开始操作后循环报错

> [server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:192)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:196)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:320)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:134)
        at com.genymobile.scrcpy.Controller.control(Controller.java:83)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:90)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
        ... 10 more

![image](https://github.com/Genymobile/scrcpy/assets/64337958/090a4f73-af8c-4209-9a18-854df8232e11)
我尝试过更换scrcpy版本为1.25 但出现了[issue #52](https://github.com/kvarenzn/phisap/issues/52 "issue #52")相同的问题 但其解决办法并不适用 此问题在我的另一台非MIUI(pixel experience)设备上并未出现

**Comment by kvarenzn** [comment]
只看报错的话应该是MIUI权限的问题。或许是因为MIUI不允许其他应用程序来注入触控事件

不过你是否有尝试过直接使用scrcpy 2.0.0？是否出现了相同的报错？

**Comment by sgg64587** [comment]
> 只看报错的话应该是MIUI权限的问题。或许是因为MIUI不允许其他应用程序来注入触控事件
> 
> 不过你是否有尝试过直接使用scrcpy 2.0.0？是否出现了相同的报错？

打扰大佬了 我已在scrcpy的issue中找到了解决方法 [issue](https://github.com/appium/appium/issues/13802#issuecomment-587802222)

**Comment by kvarenzn** [comment]
解决了就好
