### ISSUE TITLE
在运行main.py时报错

### ISSUE THREAD

**Issue by gsmabc** [kvarenzn/phisap#71]
依使用说明运行，发生如下报错：
报错内容：Traceback (most recent call last):
  File "C:\Users\15055300201\Desktop\phiap\phisap-main\phisap-main\main.py", line 7, in <module>
    from algo.algo_base import TouchEvent
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15055300201\Desktop\phiap\phisap-main\phisap-main\algo\algo_base.py", line 2, in <module>
    from typing import Self, IO
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'Self' from 'typing' (C:\Program Files\Python311\lib\typing.py)
运行平台：Windows 11 21H2家庭版
python版本：3.11.0a2

**Comment by kvarenzn** [comment]
？还真有人用python开发预览版啊，我寻思3.11.0不都发布半年多了么
PEP 673这个特性3.11.0a2还没加，如果你非要用预览版，请用`3.11.0a5`及以后的版本
