### ISSUE TITLE
关于Arcaea操作的包导入报错

### ISSUE THREAD

**Issue by RaTaiHok** [kvarenzn/phisap#83]
包导入错误是怎么解决
*我将文件夹名改为了arcaea
D:\[Phigros Manage\phisap-main\arcaea>py main.py
Traceback (most recent call last):
  File "D:\[Phigros Manage\phisap-main\arcaea\main.py", line 3, in <module>
    from .chart import Chart
ImportError: attempted relative import with no known parent package

D:\[Phigros Manage\phisap-main\arcaea>py chart.py
Traceback (most recent call last):
  File "D:\[Phigros Manage\phisap-main\arcaea\chart.py", line 3, in <module>
    from ..easing import Easing3D
ImportError: attempted relative import with no known parent package

**Comment by kvarenzn** [comment]
可能已经修复，请更新后测试
顺便一提，我已经很长时间没碰过arcaea了，所以对最新版程序的支持可能存在一些问题。如果你遇到了，请再开issue，并附上必要信息
